# Generated by Django 4.2 on 2023-05-02 10:14

import deposit.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Halfyearly', 'Halfyearly'), ('Yearly', 'Yearly')], default=deposit.utils.InterestTypes['Monthly'], max_length=10)),
                ('deposited_on', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('withdrawn_on', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_deposit', to=settings.AUTH_USER_MODEL)),
                ('kyc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kyc.kyc')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_deposit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
