# Generated by Django 4.2 on 2023-05-12 11:42

import deposit.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0002_kyc_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('interest_type', models.CharField(choices=[('3 Months', 'ThreeMonths'), ('6 Months', 'SixMonths'), ('12 Months', 'TwelveMonths'), ('24 Months', 'TwentyFourMonths')], default=deposit.utils.InterestTypes['TwelveMonths'], max_length=10)),
                ('deposited_on', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('withdrawn_on', models.DateTimeField()),
                ('roi', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_deposit', to=settings.AUTH_USER_MODEL)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='kyc.kyc')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_deposit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
