# Generated by Django 4.2 on 2023-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='roi',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
