# Generated by Django 4.2 on 2023-05-12 12:53

import deposit.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_alter_deposit_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='interest_type',
            field=models.CharField(choices=[('3 Months', 'ThreeMonths'), ('6 Months', 'SixMonths'), ('12 Months', 'TwelveMonths'), ('18 Months', 'EighteenMonths'), ('24 Months', 'TwentyFourMonths')], default=deposit.utils.InterestTypes['TwelveMonths'], max_length=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='withdrawn_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
