# Generated by Django 4.2 on 2023-05-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_alter_deposit_interest_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='withdrawn_on',
        ),
        migrations.AddField(
            model_name='deposit',
            name='maturity_term',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
