# Generated by Django 4.2 on 2023-05-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0005_alter_deposit_deposited_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposited_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='maturity_term',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
