# Generated by Django 4.2 on 2023-05-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0007_alter_deposit_kyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('due_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payable', to='deposit.deposit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
