# Generated by Django 4.2 on 2023-05-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0010_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
