# Generated by Django 4.2 on 2023-05-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0011_alter_payment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payable',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payable',
            name='payable_amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
