# Generated by Django 4.2 on 2023-05-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0012_alter_payable_active_alter_payable_payable_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payable',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
