# Generated by Django 4.2 on 2023-05-02 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loan.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_type', models.CharField(choices=[('EMI', 'Emi'), ('Term Loan', 'Termloan')], default=loan.utils.InterestTypes['Emi'], max_length=10)),
                ('loan_date_on', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('loan_closed_on', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_loan', to=settings.AUTH_USER_MODEL)),
                ('kyc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kyc.kyc')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_loan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
