# Generated by Django 4.2 on 2023-05-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('due_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due', to='loan.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('active', models.BooleanField(default=False)),
                ('due', models.ManyToManyField(blank=True, null=True, to='loan.due')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
