# Generated by Django 4.2 on 2023-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_due_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
