# Generated by Django 4.2 on 2023-05-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_receipt_due_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='due',
            field=models.ManyToManyField(blank=True, null=True, to='loan.due'),
        ),
    ]
