# Generated by Django 4.2 on 2023-05-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_loan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
