# Generated by Django 4.2 on 2023-05-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholder',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
