# Generated by Django 4.2 on 2023-05-17 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kyc_slug'),
        ('shareholder', '0002_alter_shareholder_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='kyc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholder', to='kyc.kyc'),
        ),
    ]
