# Generated by Django 4.2 on 2023-05-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharetype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetype',
            name='share_type',
            field=models.CharField(choices=[('Equity', 'Equity'), ('Pref', 'Pref')], max_length=10),
        ),
    ]
