# Generated by Django 4.2 on 2023-05-03 10:58

from django.db import migrations, models
import sharetype.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sharetype', '0002_alter_sharetype_share_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetype',
            name='share_type',
            field=models.CharField(choices=[('Equity', 'Equity'), ('Pref', 'Pref')], default=sharetype.utils.ShareTypes['Pref'], max_length=10),
        ),
    ]
