# Generated by Django 4.2 on 2023-05-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='pan',
            field=models.CharField(max_length=10),
        ),
    ]
