# Generated by Django 4.2 on 2023-05-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_kyc_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='pan',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
