# Generated by Django 4.2 on 2023-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kyc_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
