# Generated by Django 4.2 on 2023-05-05 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_alter_kyc_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^(?:(?:\\+|0{0,2})91(\\s*[\\ -]\\s*)?|[0]?)?[789]\\d{9}|(\\d[ -]?){10}\\d$', message='Enter a Valid Indian Phone Number')]),
        ),
    ]
